/*
389. Find the Difference   
https://leetcode.com/problems/find-the-difference/
Difficulty: Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added. 

@param {string} s
@param {string} t
@return {character}
*/

var findTheDifference = function(s, t) {
    s=s.split("");
    t=t.split("");
    s.sort();
    t.sort();
    var i=0;
    while (s[i]===t[i]){
        i++;
    }
    return t[i];
};
